# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RACDemo_Objc' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'ReactiveCocoa', '~> 2.5'
pod 'Masonry', '~> 1.0.2'
pod 'VTMagic'
  # Pods for RACDemo_Objc

end
